### ISSUE TITLE
Do I need to keep my car running?

### ISSUE THREAD

**Issue by shalak** [steve192/dashcam-transporter#9]
Hi! How does the usual sync workflow look like? I park in the garage, the WiFi connects, starts to sync, but then I turn off the car and the download is interrupted? Or do Viofo dashcams come with some battery that keeps it alive until the download is finished?

**Comment by Nicxx2** [comment]
Hello @shalak 👋 

I am also planning to install my viofo a129 plus in my car.

Basically I will use a  "VIOFO HK5 Acc Hardwire Kit". This is the hardwire kit that will allow the dashcam to keep working when the car is turned off by connecting the camera to the car's fuse box.

**Comment by shalak** [comment]
> will allow the dashcam to keep working when the car is turned off by connecting the camera to the car's fuse box

So essentially you'll have to manually turn off the dashcam or risk that it will drain your car battery completely?

**Comment by Nicxx2** [comment]
Hey @shalak,

The VIOFO HK5 Acc Hardwire Kit actually has built-in voltage cut-off protection. This means you don't have to manually turn off the dashcam at all. The kit monitors your car's battery and will automatically power down the dashcam when it detects the voltage dropping below a certain threshold, which prevents your car battery from being drained. It's a super helpful feature, especially for parking mode, where you want the dashcam to keep running but without risking a flat battery. So, you can just leave it and it’ll manage itself. 

The hardwire kit also gives you some flexibility with different cut-off voltage options. For example, if you want the safest setting to protect your car battery, I'd recommend setting it to the 12.4V option. That way, it’ll shut off earlier to ensure your car’s battery stays healthy. If you need the dashcam to last longer in parking mode (for around 4-5 days, for example), you can go with 12.0V, but just keep in mind it’ll drain the battery a bit more before turning off.

**Comment by steve192** [comment]
> Hi! How does the usual sync workflow look like? I park in the garage, the WiFi connects, starts to sync, but then I turn off the car and the download is interrupted? Or do Viofo dashcams come with some battery that keeps it alive until the download is finished?

Hi, to sync the video files, the camera has to stay on during the sync. The sync is started as soon as the WiFi of the camera is found.
The viofo a119 only has an internal battery for a few seconds to ensure videos are not corrupted after power loss.

I personally use a raspberry pi with a Powerbank that I occasionally bring into the car.
